# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'driver_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DriverGui(object):
    def setupUi(self, DriverGui):
        DriverGui.setObjectName("DriverGui")
        DriverGui.resize(800, 400)
        self.switchMode = QtWidgets.QPushButton(DriverGui)
        self.switchMode.setGeometry(QtCore.QRect(20, 300, 80, 80))
        self.switchMode.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(144, 144, 144);")
        self.switchMode.setObjectName("switchMode")
        self.stackedWidget = QtWidgets.QStackedWidget(DriverGui)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 400))
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidget.raise_()
        self.switchMode.raise_()

        self.retranslateUi(DriverGui)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(DriverGui)

    def retranslateUi(self, DriverGui):
        _translate = QtCore.QCoreApplication.translate
        DriverGui.setWindowTitle(_translate("DriverGui", "Dialog"))
        self.switchMode.setText(_translate("DriverGui", "Mode"))
